name: vetore
description: "vetore is a coffee shop app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cached_network_image: ^3.1.0
  url_launcher: ^6.2.6
  color_hex: ^0.0.1
  hexcolor: ^3.0.1
  image_card: ^0.0.4
  banner_image: ^1.0.7
  carousel_images: ^1.1.2
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/coffee_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/coffee_icon.jpg"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
